# Generated by Django 2.2.7 on 2019-11-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pred_count', models.CharField(max_length=10)),
                ('left_hand', models.BooleanField()),
                ('true_count', models.IntegerField(null=True)),
            ],
        ),
    ]
