# Generated by Django 2.2.7 on 2019-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pred_count', models.IntegerField()),
                ('true_count', models.IntegerField(null=True)),
            ],
        ),
    ]
